### ISSUE TITLE
Unable to add temperature/humidity-sensor

### ISSUE THREAD

**Issue by StefanO-Kjell** [nlrb/com.weather-sensors#52] opened 2019-01-06 09:35 UTC
On latest version v.2.0.1 I'm unable to add a temperature/humidity-senso. It just says "Invalid setting type! Got number but expected string (label) for id.

Any idea?

**Comment by nlrb** [comment] 2019-01-06 09:41
Duplicate of #51.

**Closed by nlrb** 2019-01-06 09:41 UTC

**Comment by StefanO-Kjell** [comment] 2019-01-06 10:14
Sorry, only checked the open issues 🙈

**Comment by nlrb** [comment] 2019-01-06 10:16
No problem, will include the fix in the next release.
