### ISSUE TITLE
Oregon weather station sensors no longer found

### ISSUE THREAD

**Issue by PatrikBrodd** [nlrb/com.weather-sensors#23] opened 2017-12-25 16:01 UTC
A time ago my homey stop showing my Oregon sensors. 
I think it was after a homey update. but I'm not sure.
I´m have installed v.1.2.2 of you're app.
The senors are working. I can se them on my Telldus znet lite v2.

Perhaps you can help me find out why?

[stats1514216129895.json.zip](https://github.com/nlrb/com.weather-sensors/files/1585982/stats1514216129895.json.zip)

**Comment by nlrb** [comment] 2017-12-25 18:18
This is a known issue, see https://github.com/athombv/homey/issues/2075.

**Comment by nlrb** [comment] 2018-02-16 18:00
Duplicate of #12.

**Closed by nlrb** 2018-02-16 18:00 UTC
